'use client';

import React, { useState, useEffect } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { 
  Plus, Edit, Trash2, Search, ArrowLeft, RefreshCw, Image as ImageIcon, 
  Package, DollarSign, Tag, Layers, CheckCircle2, AlertCircle, X, Upload, Copy, Check, Terminal, ExternalLink, Star, Flame, Lock, Key, LogOut
} from 'lucide-react';
import { 
  fetchProducts, addProduct, updateProduct, deleteProduct, toggleFeaturedProduct, togglePopularProduct,
  seedDummyProductsToSupabase, uploadProductImage, checkTableExists, Product 
} from '@/lib/products';
import styles from './Admin.module.css';

const CATEGORIES = ['T-Shirt', 'Hoodie', 'Jersey', 'Performance', 'Pants', 'Hat', 'Accessories'];
const AVAILABLE_SIZES = ['S', 'M', 'L', 'XL', 'XXL', '3XL', 'One Size', 'S/M', 'L/XL'];

const SETUP_SQL = `-- Run this query in Supabase SQL Editor to ensure columns and permissions are set up:

CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC NOT NULL,
  image TEXT NOT NULL,
  description TEXT,
  sizes TEXT[] DEFAULT ARRAY['S', 'M', 'L', 'XL'],
  is_featured BOOLEAN DEFAULT FALSE,
  is_popular BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_popular BOOLEAN DEFAULT FALSE;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW());

-- Grant full table & sequence permissions to anon/authenticated roles
GRANT ALL ON TABLE public.products TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- Disable Row Level Security
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
`;

export default function AdminPage() {
  // Authentication State
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [passwordInput, setPasswordInput] = useState('');
  const [authError, setAuthError] = useState('');

  const [products, setProducts] = useState<Product[]>([]);
  const [loading, setLoading] = useState(true);
  const [tableExists, setTableExists] = useState<boolean | null>(null);
  const [showSqlModal, setShowSqlModal] = useState(false);
  const [copiedSql, setCopiedSql] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategoryFilter, setSelectedCategoryFilter] = useState('ALL');
  const [notification, setNotification] = useState<{ type: 'success' | 'error'; message: string } | null>(null);

  // Modals state
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [editingProduct, setEditingProduct] = useState<Product | null>(null);
  const [deletingProduct, setDeletingProduct] = useState<Product | null>(null);

  // Form state for Add/Edit
  const [formData, setFormData] = useState({
    name: '',
    category: 'T-Shirt',
    price: '',
    image: '',
    description: '',
    is_featured: false,
    is_popular: false,
    sizes: ['S', 'M', 'L', 'XL'] as string[]
  });
  const [uploadingImage, setUploadingImage] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    // Check if already authenticated in sessionStorage
    const savedAuth = typeof window !== 'undefined' ? localStorage.getItem('admin_authenticated') : null;
    if (savedAuth === 'true') {
      setIsAuthenticated(true);
      loadProducts();
    }
  }, []);

  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    const correctPassword = process.env.NEXT_PUBLIC_ADMIN_PASSWORD || 'admin123';
    
    if (passwordInput === correctPassword) {
      setIsAuthenticated(true);
      if (typeof window !== 'undefined') {
        localStorage.setItem('admin_authenticated', 'true');
      }
      setAuthError('');
      loadProducts();
    } else {
      setAuthError('Incorrect Password! Please try again.');
    }
  };

  const handleLogout = () => {
    setIsAuthenticated(false);
    if (typeof window !== 'undefined') {
      localStorage.removeItem('admin_authenticated');
    }
    setPasswordInput('');
  };

  const loadProducts = async () => {
    setLoading(true);
    const exists = await checkTableExists();
    setTableExists(exists);
    const data = await fetchProducts();
    setProducts(data);
    setLoading(false);
  };

  const showToast = (type: 'success' | 'error', message: string) => {
    setNotification({ type, message });
    setTimeout(() => {
      setNotification(null);
    }, 6000);
  };

  const handleCopySql = () => {
    navigator.clipboard.writeText(SETUP_SQL);
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 3000);
  };

  // Open Add Modal
  const handleOpenAddModal = () => {
    setFormData({
      name: '',
      category: 'T-Shirt',
      price: '',
      image: '',
      description: '',
      is_featured: true,
      is_popular: true,
      sizes: ['S', 'M', 'L', 'XL']
    });
    setIsAddModalOpen(true);
  };

  // Open Edit Modal
  const handleOpenEditModal = (product: Product) => {
    setEditingProduct(product);
    setFormData({
      name: product.name,
      category: product.category,
      price: product.price.toString(),
      image: product.image,
      description: product.description || '',
      is_featured: Boolean(product.is_featured),
      is_popular: Boolean(product.is_popular),
      sizes: [...product.sizes]
    });
  };

  // Quick Toggle Featured Flag
  const handleToggleFeatured = async (product: Product) => {
    const newFeaturedState = !product.is_featured;
    const res = await toggleFeaturedProduct(product.id, newFeaturedState);
    if (res.success) {
      const updatedProduct = res.data || { ...product, is_featured: newFeaturedState };
      setProducts(prev => prev.map(p => p.id === product.id ? updatedProduct : p));
      showToast('success', `Product "${product.name}" ${newFeaturedState ? 'marked as Featured ⭐' : 'removed from Featured'}`);
    } else {
      showToast('error', res.error || 'Failed to update featured status');
    }
  };

  // Quick Toggle Popular Flag
  const handleTogglePopular = async (product: Product) => {
    const newPopularState = !product.is_popular;
    const res = await togglePopularProduct(product.id, newPopularState);
    if (res.success) {
      const updatedProduct = res.data || { ...product, is_popular: newPopularState };
      setProducts(prev => prev.map(p => p.id === product.id ? updatedProduct : p));
      showToast('success', `Product "${product.name}" ${newPopularState ? 'marked as Popular 🔥' : 'removed from Popular'}`);
    } else {
      showToast('error', res.error || 'Failed to update popular status');
    }
  };

  // Handle File Upload
  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setUploadingImage(true);
    try {
      const url = await uploadProductImage(file);
      setFormData(prev => ({ ...prev, image: url }));
      showToast('success', 'Image uploaded successfully!');
    } catch (err) {
      showToast('error', 'Failed to upload image');
    } finally {
      setUploadingImage(false);
    }
  };

  // Handle Size Checkbox Toggle
  const handleSizeToggle = (size: string) => {
    setFormData(prev => {
      const exists = prev.sizes.includes(size);
      if (exists) {
        return { ...prev, sizes: prev.sizes.filter(s => s !== size) };
      } else {
        return { ...prev, sizes: [...prev.sizes, size] };
      }
    });
  };

  // Submit Add Product Form
  const handleAddSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.name.trim() || !formData.price || !formData.image.trim()) {
      showToast('error', 'Please fill in required fields: Name, Price, and Image');
      return;
    }

    setSubmitting(true);
    const res = await addProduct({
      name: formData.name.trim(),
      category: formData.category,
      price: parseFloat(formData.price),
      image: formData.image.trim(),
      description: formData.description.trim(),
      is_featured: formData.is_featured,
      is_popular: formData.is_popular,
      sizes: formData.sizes.length > 0 ? formData.sizes : ['S', 'M', 'L', 'XL']
    });

    setSubmitting(false);

    if (res.success && res.data) {
      setProducts(prev => [res.data!, ...prev]);
      setIsAddModalOpen(false);
      setTableExists(true);
      showToast('success', `Product "${res.data.name}" added to Supabase & Shop!`);
    } else {
      showToast('error', res.error || 'Failed to create product in Supabase');
      if (res.error?.includes('Table Missing')) {
        setShowSqlModal(true);
      }
    }
  };

  // Submit Edit Product Form
  const handleEditSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!editingProduct) return;
    if (!formData.name.trim() || !formData.price || !formData.image.trim()) {
      showToast('error', 'Name, Price, and Image cannot be empty');
      return;
    }

    setSubmitting(true);
    const res = await updateProduct(editingProduct.id, {
      name: formData.name.trim(),
      category: formData.category,
      price: parseFloat(formData.price),
      image: formData.image.trim(),
      description: formData.description.trim(),
      is_featured: formData.is_featured,
      is_popular: formData.is_popular,
      sizes: formData.sizes
    });
    setSubmitting(false);

    if (res.success && res.data) {
      setProducts(prev => prev.map(p => p.id === editingProduct.id ? res.data! : p));
      setEditingProduct(null);
      showToast('success', `Product "${res.data.name}" updated successfully!`);
    } else {
      showToast('error', res.error || 'Failed to update product in Supabase');
    }
  };

  // Confirm Delete Product
  const handleDeleteConfirm = async () => {
    if (!deletingProduct) return;
    setSubmitting(true);
    const res = await deleteProduct(deletingProduct.id);
    setSubmitting(false);

    if (res.success) {
      setProducts(prev => prev.filter(p => p.id !== deletingProduct.id));
      showToast('success', `Product "${deletingProduct.name}" deleted successfully!`);
      setDeletingProduct(null);
    } else {
      showToast('error', res.error || 'Failed to delete product');
    }
  };

  // LOGIN LOCK OVERLAY IF NOT AUTHENTICATED
  if (!isAuthenticated) {
    return (
      <div className={styles.adminContainer} style={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
        <div style={{
          background: '#161b22',
          border: '1px solid #30363d',
          borderRadius: '16px',
          padding: '2.5rem',
          width: '100%',
          maxWidth: '420px',
          boxShadow: '0 20px 50px rgba(0,0,0,0.7)',
          textAlign: 'center'
        }}>
          <div style={{
            width: '64px',
            height: '64px',
            borderRadius: '50%',
            background: 'rgba(211, 47, 47, 0.15)',
            color: '#ff4b4b',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            margin: '0 auto 1.25rem'
          }}>
            <Lock size={32} />
          </div>

          <h2 style={{ fontSize: '1.5rem', fontWeight: 800, color: '#f0f6fc', marginBottom: '0.4rem' }}>
            Admin Security Lock
          </h2>
          <p style={{ color: '#8b949e', fontSize: '0.9rem', marginBottom: '1.75rem' }}>
            Enter your secret Admin Password to access product dashboard.
          </p>

          {authError && (
            <div style={{
              background: 'rgba(218, 54, 51, 0.2)',
              border: '1px solid #da3633',
              color: '#f85149',
              padding: '0.65rem',
              borderRadius: '8px',
              fontSize: '0.85rem',
              marginBottom: '1.25rem',
              fontWeight: 600
            }}>
              {authError}
            </div>
          )}

          <form onSubmit={handleLogin}>
            <div style={{ position: 'relative', marginBottom: '1.5rem' }}>
              <input 
                type="password"
                placeholder="Enter Admin Password..."
                className={styles.formInput}
                style={{ paddingLeft: '2.6rem' }}
                value={passwordInput}
                onChange={(e) => setPasswordInput(e.target.value)}
                autoFocus
                required
              />
              <Key size={18} color="#8b949e" style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)' }} />
            </div>

            <button type="submit" className={styles.primaryButton} style={{ width: '100%', justifyContent: 'center', padding: '0.85rem' }}>
              Unlock Dashboard
            </button>
          </form>

          <p style={{ marginTop: '1.5rem', fontSize: '0.78rem', color: '#6e7681' }}>
            Default Password: <code style={{ color: '#58a6ff' }}>admin123</code>
          </p>
        </div>
      </div>
    );
  }

  // Filtered Products
  const filteredProducts = products.filter(p => {
    const matchesSearch = p.name.toLowerCase().includes(searchQuery.toLowerCase()) || 
                          p.category.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesCat = selectedCategoryFilter === 'ALL' || p.category === selectedCategoryFilter;
    return matchesSearch && matchesCat;
  });

  const totalProducts = products.length;
  const featuredCount = products.filter(p => p.is_featured).length;
  const popularCount = products.filter(p => p.is_popular).length;
  const categoriesCount = new Set(products.map(p => p.category)).size;
  const avgPrice = totalProducts > 0 
    ? (products.reduce((acc, p) => acc + p.price, 0) / totalProducts).toFixed(2) 
    : '0.00';

  return (
    <div className={styles.adminContainer}>
      <div className={styles.adminWrapper}>
        
        {/* Notification Toast */}
        {notification && (
          <div 
            style={{
              position: 'fixed',
              top: '20px',
              right: '20px',
              zIndex: 1000,
              background: notification.type === 'success' ? '#238636' : '#da3633',
              color: '#fff',
              padding: '0.9rem 1.4rem',
              borderRadius: '8px',
              display: 'flex',
              alignItems: 'center',
              gap: '0.6rem',
              boxShadow: '0 8px 24px rgba(0,0,0,0.5)',
              fontWeight: 600,
              maxWidth: '500px'
            }}
          >
            {notification.type === 'success' ? <CheckCircle2 size={20} /> : <AlertCircle size={20} />}
            <span>{notification.message}</span>
          </div>
        )}

        {/* Missing Table Banner */}
        {tableExists === false && (
          <div style={{
            background: 'rgba(218, 54, 51, 0.15)',
            border: '1px solid #da3633',
            borderRadius: '12px',
            padding: '1.25rem 1.5rem',
            marginBottom: '2rem',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: '1rem',
            flexWrap: 'wrap'
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
              <AlertCircle size={28} color="#f85149" />
              <div>
                <h4 style={{ margin: 0, color: '#f85149', fontSize: '1.05rem', fontWeight: 700 }}>
                  Supabase Setup Required: 'products' table missing
                </h4>
                <p style={{ margin: '0.25rem 0 0 0', color: '#c9d1d9', fontSize: '0.9rem' }}>
                  Please run the 1-click SQL script in your Supabase SQL Editor to enable database saving.
                </p>
              </div>
            </div>
            <button 
              onClick={() => setShowSqlModal(true)} 
              className={styles.primaryButton}
              style={{ background: '#d32f2f' }}
            >
              <Terminal size={18} /> View SQL Script
            </button>
          </div>
        )}

        {/* Header Section */}
        <div className={styles.headerSection}>
          <div>
            <h1 className={styles.headerTitle}>
              <Layers size={32} /> Admin Product Dashboard
            </h1>
            <p className={styles.headerSubtitle}>
              Manage product catalog, prices, categories, images, featured & popular items.
            </p>
          </div>

          <div className={styles.headerActions}>
            <Link href="/products" className={styles.secondaryButton}>
              <ArrowLeft size={18} /> View Store
            </Link>
            <button onClick={handleOpenAddModal} className={styles.primaryButton}>
              <Plus size={20} /> Add New Product
            </button>
          </div>
        </div>

        {/* Stats Grid */}
        <div className={styles.statsGrid}>
          <div className={styles.statCard}>
            <div className={styles.statIconWrapper}>
              <Package size={28} />
            </div>
            <div className={styles.statInfo}>
              <span className={styles.statLabel}>Total Products</span>
              <span className={styles.statValue}>{totalProducts}</span>
            </div>
          </div>

          <div className={styles.statCard}>
            <div className={styles.statIconWrapper} style={{ background: 'rgba(255, 215, 0, 0.15)', color: '#ffd700' }}>
              <Star size={28} />
            </div>
            <div className={styles.statInfo}>
              <span className={styles.statLabel}>Featured Items</span>
              <span className={styles.statValue}>{featuredCount}</span>
            </div>
          </div>

          <div className={styles.statCard}>
            <div className={styles.statIconWrapper} style={{ background: 'rgba(255, 120, 0, 0.15)', color: '#ff7800' }}>
              <Flame size={28} />
            </div>
            <div className={styles.statInfo}>
              <span className={styles.statLabel}>Popular Items</span>
              <span className={styles.statValue}>{popularCount}</span>
            </div>
          </div>

          <div className={styles.statCard}>
            <div className={styles.statIconWrapper} style={{ background: 'rgba(63, 185, 80, 0.15)', color: '#3fb950' }}>
              <DollarSign size={28} />
            </div>
            <div className={styles.statInfo}>
              <span className={styles.statLabel}>Average Price</span>
              <span className={styles.statValue}>${avgPrice}</span>
            </div>
          </div>
        </div>

        {/* Toolbar / Search & Filter */}
        <div className={styles.toolbar}>
          <div className={styles.searchBox}>
            <Search size={18} color="#8b949e" />
            <input 
              type="text" 
              placeholder="Search products by name or category..." 
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </div>

          <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center' }}>
            <span style={{ fontSize: '0.85rem', color: '#8b949e' }}>Category:</span>
            <select 
              className={styles.categorySelect}
              value={selectedCategoryFilter}
              onChange={(e) => setSelectedCategoryFilter(e.target.value)}
            >
              <option value="ALL">All Categories</option>
              {CATEGORIES.map(cat => (
                <option key={cat} value={cat}>{cat}</option>
              ))}
            </select>
          </div>
        </div>

        {/* Product Table */}
        <div className={styles.tableCard}>
          {loading ? (
            <div className={styles.emptyState}>
              <RefreshCw className="animate-spin" size={32} style={{ margin: '0 auto 1rem', animation: 'spin 1s linear infinite' }} />
              <p>Loading products from Supabase...</p>
            </div>
          ) : filteredProducts.length === 0 ? (
            <div className={styles.emptyState}>
              <Package size={48} className={styles.emptyStateIcon} />
              <h3>No products found</h3>
              <p style={{ marginTop: '0.5rem' }}>Try adjusting your search or click "Add New Product" to add one.</p>
            </div>
          ) : (
            <div className={styles.tableWrapper}>
              <table className={styles.table}>
                <thead>
                  <tr>
                    <th>Product</th>
                    <th>Landing Display</th>
                    <th>Category</th>
                    <th>Price</th>
                    <th>Sizes</th>
                    <th style={{ textAlign: 'right' }}>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredProducts.map((product, idx) => (
                    <tr key={`admin-prod-${product.id}-${idx}`}>
                      <td>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.9rem' }}>
                          <img 
                            src={product.image || '/hoodie_logo_image.png'} 
                            alt={product.name} 
                            className={styles.productThumb}
                            onError={(e) => {
                              (e.target as HTMLElement).setAttribute('src', '/hoodie_logo_image.png');
                            }}
                          />
                          <div>
                            <div className={styles.productNameText}>{product.name}</div>
                            <div style={{ fontSize: '0.78rem', color: '#8b949e', marginTop: '0.2rem' }}>ID: {product.id}</div>
                          </div>
                        </div>
                      </td>
                      <td>
                        <div style={{ display: 'flex', gap: '0.4rem', flexWrap: 'wrap' }}>
                          <button
                            onClick={() => handleToggleFeatured(product)}
                            style={{
                              background: product.is_featured ? 'rgba(255, 215, 0, 0.2)' : '#0d1117',
                              color: product.is_featured ? '#ffd700' : '#8b949e',
                              border: product.is_featured ? '1px solid #ffd700' : '1px solid #30363d',
                              padding: '0.3rem 0.55rem',
                              borderRadius: '20px',
                              fontSize: '0.75rem',
                              fontWeight: 'bold',
                              cursor: 'pointer',
                              display: 'inline-flex',
                              alignItems: 'center',
                              gap: '0.25rem'
                            }}
                            title="Toggle Landing Page Featured status"
                          >
                            <Star size={13} fill={product.is_featured ? '#ffd700' : 'none'} />
                            {product.is_featured ? 'Featured' : 'Featured'}
                          </button>

                          <button
                            onClick={() => handleTogglePopular(product)}
                            style={{
                              background: product.is_popular ? 'rgba(255, 120, 0, 0.2)' : '#0d1117',
                              color: product.is_popular ? '#ff7800' : '#8b949e',
                              border: product.is_popular ? '1px solid #ff7800' : '1px solid #30363d',
                              padding: '0.3rem 0.55rem',
                              borderRadius: '20px',
                              fontSize: '0.75rem',
                              fontWeight: 'bold',
                              cursor: 'pointer',
                              display: 'inline-flex',
                              alignItems: 'center',
                              gap: '0.25rem'
                            }}
                            title="Toggle Landing Page Popular status"
                          >
                            <Flame size={13} fill={product.is_popular ? '#ff7800' : 'none'} />
                            {product.is_popular ? 'Popular' : 'Popular'}
                          </button>
                        </div>
                      </td>
                      <td>
                        <span className={styles.categoryBadge}>{product.category}</span>
                      </td>
                      <td>
                        <span className={styles.priceTag}>${product.price.toFixed(2)}</span>
                      </td>
                      <td>
                        <div className={styles.sizesTag}>
                          {product.sizes.map(s => (
                            <span key={s} className={styles.sizeChip}>{s}</span>
                          ))}
                        </div>
                      </td>
                      <td>
                        <div className={styles.actionButtons} style={{ justifyContent: 'flex-end' }}>
                          <button 
                            className={styles.editBtn}
                            onClick={() => handleOpenEditModal(product)}
                            title="Edit Product (Title, Price, Image)"
                          >
                            <Edit size={16} /> Edit
                          </button>
                          <button 
                            className={styles.deleteBtn}
                            onClick={() => setDeletingProduct(product)}
                            title="Delete Product"
                          >
                            <Trash2 size={16} /> Delete
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>

        {/* SQL SETUP MODAL */}
        {showSqlModal && (
          <div className={styles.modalOverlay}>
            <div className={styles.modalContent} style={{ maxWidth: '680px' }}>
              <div className={styles.modalHeader}>
                <h3 className={styles.modalTitle}>
                  <Terminal size={22} color="#58a6ff" /> Supabase SQL Table Setup
                </h3>
                <button className={styles.closeModalBtn} onClick={() => setShowSqlModal(false)}>
                  <X size={20} />
                </button>
              </div>

              <p style={{ color: '#c9d1d9', fontSize: '0.95rem', lineHeight: '1.5' }}>
                Open your Supabase Project dashboard, go to <strong>SQL Editor</strong>, paste this script and click <strong>RUN</strong>:
              </p>

              <div style={{
                position: 'relative',
                background: '#0d1117',
                border: '1px solid #30363d',
                borderRadius: '8px',
                padding: '1rem',
                margin: '1rem 0'
              }}>
                <button 
                  onClick={handleCopySql}
                  className={styles.primaryButton}
                  style={{
                    position: 'absolute',
                    top: '12px',
                    right: '12px',
                    padding: '0.4rem 0.8rem',
                    fontSize: '0.8rem',
                    background: copiedSql ? '#238636' : '#21262d',
                    border: '1px solid #30363d'
                  }}
                >
                  {copiedSql ? <Check size={14} /> : <Copy size={14} />}
                  {copiedSql ? 'Copied!' : 'Copy SQL'}
                </button>
                <pre style={{
                  color: '#58a6ff',
                  fontSize: '0.82rem',
                  fontFamily: 'monospace',
                  overflowX: 'auto',
                  margin: 0,
                  maxHeight: '260px'
                }}>
                  {SETUP_SQL}
                </pre>
              </div>

              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '1.25rem' }}>
                <a 
                  href="https://supabase.com/dashboard/project/xixdylkqqyvagpdlglay/sql/new" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className={styles.secondaryButton}
                >
                  Open Supabase SQL Editor <ExternalLink size={16} />
                </a>

                <button 
                  className={styles.primaryButton} 
                  onClick={() => {
                    setShowSqlModal(false);
                    loadProducts();
                  }}
                >
                  Done / Recheck Table
                </button>
              </div>
            </div>
          </div>
        )}

        {/* ADD PRODUCT MODAL */}
        {isAddModalOpen && (
          <div className={styles.modalOverlay}>
            <div className={styles.modalContent}>
              <div className={styles.modalHeader}>
                <h3 className={styles.modalTitle}>
                  <Plus size={22} color="#ff4b4b" /> Add New Product
                </h3>
                <button className={styles.closeModalBtn} onClick={() => setIsAddModalOpen(false)}>
                  <X size={20} />
                </button>
              </div>

              <form onSubmit={handleAddSubmit}>
                <div className={styles.formGroup}>
                  <label className={styles.formLabel}>Product Name *</label>
                  <input 
                    type="text" 
                    className={styles.formInput}
                    placeholder="e.g. HOODED SWEATSHIRT"
                    value={formData.name}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                    required
                  />
                </div>

                <div className={styles.formRow}>
                  <div className={styles.formGroup}>
                    <label className={styles.formLabel}>Price ($) *</label>
                    <input 
                      type="number" 
                      step="0.01"
                      min="0"
                      className={styles.formInput}
                      placeholder="e.g. 29.99"
                      value={formData.price}
                      onChange={(e) => setFormData({ ...formData, price: e.target.value })}
                      required
                    />
                  </div>

                  <div className={styles.formGroup}>
                    <label className={styles.formLabel}>Category *</label>
                    <select 
                      className={styles.formSelect}
                      value={formData.category}
                      onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                    >
                      {CATEGORIES.map(cat => (
                        <option key={cat} value={cat}>{cat}</option>
                      ))}
                    </select>
                  </div>
                </div>

                <div className={styles.formGroup}>
                  <label className={styles.formLabel}>Product Image *</label>
                  <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '0.5rem' }}>
                    <input 
                      type="text" 
                      className={styles.formInput}
                      placeholder="Paste Image URL or upload below..."
                      value={formData.image}
                      onChange={(e) => setFormData({ ...formData, image: e.target.value })}
                    />
                    <label className={styles.secondaryButton} style={{ cursor: 'pointer', whiteSpace: 'nowrap' }}>
                      <Upload size={16} /> {uploadingImage ? 'Uploading...' : 'Upload'}
                      <input type="file" accept="image/*" onChange={handleFileUpload} style={{ display: 'none' }} />
                    </label>
                  </div>
                  {formData.image && (
                    <img src={formData.image} alt="Preview" className={styles.imagePreview} />
                  )}
                </div>

                <div className={styles.formGroup} style={{ display: 'flex', gap: '1.5rem', flexWrap: 'wrap' }}>
                  <label className={styles.formLabel} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer', textTransform: 'none', fontSize: '0.9rem', color: '#ffd700' }}>
                    <input 
                      type="checkbox"
                      checked={formData.is_featured}
                      onChange={(e) => setFormData({ ...formData, is_featured: e.target.checked })}
                      style={{ width: '18px', height: '18px', accentColor: '#ffd700' }}
                    />
                    ⭐ Show in Featured Items
                  </label>

                  <label className={styles.formLabel} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer', textTransform: 'none', fontSize: '0.9rem', color: '#ff7800' }}>
                    <input 
                      type="checkbox"
                      checked={formData.is_popular}
                      onChange={(e) => setFormData({ ...formData, is_popular: e.target.checked })}
                      style={{ width: '18px', height: '18px', accentColor: '#ff7800' }}
                    />
                    🔥 Show in Popular Items
                  </label>
                </div>

                <div className={styles.formGroup}>
                  <label className={styles.formLabel}>Description</label>
                  <textarea 
                    className={styles.formTextarea}
                    rows={3}
                    placeholder="Enter detailed product description..."
                    value={formData.description}
                    onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  />
                </div>

                <div className={styles.formGroup}>
                  <label className={styles.formLabel}>Available Sizes</label>
                  <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem', marginTop: '0.3rem' }}>
                    {AVAILABLE_SIZES.map(size => {
                      const selected = formData.sizes.includes(size);
                      return (
                        <button
                          key={size}
                          type="button"
                          onClick={() => handleSizeToggle(size)}
                          style={{
                            padding: '0.4rem 0.8rem',
                            borderRadius: '6px',
                            border: selected ? '1px solid #ff4b4b' : '1px solid #30363d',
                            background: selected ? 'rgba(255, 75, 75, 0.2)' : '#0d1117',
                            color: selected ? '#ff4b4b' : '#c9d1d9',
                            fontWeight: '600',
                            fontSize: '0.85rem',
                            cursor: 'pointer'
                          }}
                        >
                          {size}
                        </button>
                      );
                    })}
                  </div>
                </div>

                <div className={styles.modalFooter}>
                  <button type="button" className={styles.secondaryButton} onClick={() => setIsAddModalOpen(false)}>
                    Cancel
                  </button>
                  <button type="submit" className={styles.primaryButton} disabled={submitting}>
                    {submitting ? 'Saving...' : 'Add Product'}
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}

        {/* EDIT PRODUCT MODAL */}
        {editingProduct && (
          <div className={styles.modalOverlay}>
            <div className={styles.modalContent}>
              <div className={styles.modalHeader}>
                <h3 className={styles.modalTitle}>
                  <Edit size={22} color="#58a6ff" /> Edit Product #{editingProduct.id}
                </h3>
                <button className={styles.closeModalBtn} onClick={() => setEditingProduct(null)}>
                  <X size={20} />
                </button>
              </div>

              <form onSubmit={handleEditSubmit}>
                <div className={styles.formGroup}>
                  <label className={styles.formLabel}>Product Name *</label>
                  <input 
                    type="text" 
                    className={styles.formInput}
                    value={formData.name}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                    required
                  />
                </div>

                <div className={styles.formRow}>
                  <div className={styles.formGroup}>
                    <label className={styles.formLabel}>Price ($) *</label>
                    <input 
                      type="number" 
                      step="0.01"
                      min="0"
                      className={styles.formInput}
                      value={formData.price}
                      onChange={(e) => setFormData({ ...formData, price: e.target.value })}
                      required
                    />
                  </div>

                  <div className={styles.formGroup}>
                    <label className={styles.formLabel}>Category *</label>
                    <select 
                      className={styles.formSelect}
                      value={formData.category}
                      onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                    >
                      {CATEGORIES.map(cat => (
                        <option key={cat} value={cat}>{cat}</option>
                      ))}
                    </select>
                  </div>
                </div>

                <div className={styles.formGroup}>
                  <label className={styles.formLabel}>Product Image *</label>
                  <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '0.5rem' }}>
                    <input 
                      type="text" 
                      className={styles.formInput}
                      value={formData.image}
                      onChange={(e) => setFormData({ ...formData, image: e.target.value })}
                    />
                    <label className={styles.secondaryButton} style={{ cursor: 'pointer', whiteSpace: 'nowrap' }}>
                      <Upload size={16} /> {uploadingImage ? 'Uploading...' : 'Upload'}
                      <input type="file" accept="image/*" onChange={handleFileUpload} style={{ display: 'none' }} />
                    </label>
                  </div>
                  {formData.image && (
                    <img src={formData.image} alt="Preview" className={styles.imagePreview} />
                  )}
                </div>

                <div className={styles.formGroup} style={{ display: 'flex', gap: '1.5rem', flexWrap: 'wrap' }}>
                  <label className={styles.formLabel} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer', textTransform: 'none', fontSize: '0.9rem', color: '#ffd700' }}>
                    <input 
                      type="checkbox"
                      checked={formData.is_featured}
                      onChange={(e) => setFormData({ ...formData, is_featured: e.target.checked })}
                      style={{ width: '18px', height: '18px', accentColor: '#ffd700' }}
                    />
                    ⭐ Show in Featured Items
                  </label>

                  <label className={styles.formLabel} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer', textTransform: 'none', fontSize: '0.9rem', color: '#ff7800' }}>
                    <input 
                      type="checkbox"
                      checked={formData.is_popular}
                      onChange={(e) => setFormData({ ...formData, is_popular: e.target.checked })}
                      style={{ width: '18px', height: '18px', accentColor: '#ff7800' }}
                    />
                    🔥 Show in Popular Items
                  </label>
                </div>

                <div className={styles.formGroup}>
                  <label className={styles.formLabel}>Description</label>
                  <textarea 
                    className={styles.formTextarea}
                    rows={3}
                    value={formData.description}
                    onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  />
                </div>

                <div className={styles.formGroup}>
                  <label className={styles.formLabel}>Available Sizes</label>
                  <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem', marginTop: '0.3rem' }}>
                    {AVAILABLE_SIZES.map(size => {
                      const selected = formData.sizes.includes(size);
                      return (
                        <button
                          key={size}
                          type="button"
                          onClick={() => handleSizeToggle(size)}
                          style={{
                            padding: '0.4rem 0.8rem',
                            borderRadius: '6px',
                            border: selected ? '1px solid #58a6ff' : '1px solid #30363d',
                            background: selected ? 'rgba(88, 166, 255, 0.2)' : '#0d1117',
                            color: selected ? '#58a6ff' : '#c9d1d9',
                            fontWeight: '600',
                            fontSize: '0.85rem',
                            cursor: 'pointer'
                          }}
                        >
                          {size}
                        </button>
                      );
                    })}
                  </div>
                </div>

                <div className={styles.modalFooter}>
                  <button type="button" className={styles.secondaryButton} onClick={() => setEditingProduct(null)}>
                    Cancel
                  </button>
                  <button type="submit" className={styles.primaryButton} disabled={submitting} style={{ background: '#238636' }}>
                    {submitting ? 'Updating...' : 'Save Changes'}
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}

        {/* DELETE CONFIRMATION MODAL */}
        {deletingProduct && (
          <div className={styles.modalOverlay}>
            <div className={styles.modalContent} style={{ maxWidth: '450px' }}>
              <div className={styles.modalHeader}>
                <h3 className={styles.modalTitle} style={{ color: '#f85149' }}>
                  <Trash2 size={22} /> Confirm Delete
                </h3>
                <button className={styles.closeModalBtn} onClick={() => setDeletingProduct(null)}>
                  <X size={20} />
                </button>
              </div>
              <p style={{ color: '#c9d1d9', lineHeight: '1.5' }}>
                Are you sure you want to delete product <strong>"{deletingProduct.name}"</strong>? This action will remove it from Supabase.
              </p>
              <div className={styles.modalFooter}>
                <button className={styles.secondaryButton} onClick={() => setDeletingProduct(null)}>
                  Cancel
                </button>
                <button className={styles.primaryButton} style={{ background: '#da3633' }} onClick={handleDeleteConfirm} disabled={submitting}>
                  {submitting ? 'Deleting...' : 'Delete Product'}
                </button>
              </div>
            </div>
          </div>
        )}

      </div>
    </div>
  );
}
